"""Relacja 1 do wielu

Revision ID: 21e2fd22a94f
Revises: a4c31a5f3fca
Create Date: 2025-11-08 06:03:51.213927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e2fd22a94f'
down_revision: Union[str, Sequence[str], None] = 'a4c31a5f3fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
