"""Relacja wiele do wielu

Revision ID: e04aaf28ec9f
Revises: 21e2fd22a94f
Create Date: 2025-11-08 06:11:37.465758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04aaf28ec9f'
down_revision: Union[str, Sequence[str], None] = '21e2fd22a94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
